---
title: "metrics"
output: html_document
date: "2024-12-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(kableExtra)

plot_palette <- c("#2596be", "#93cbac")
```

```{r}
mmovies <- read_csv("processed_data/metrics/metrics_movies.csv", col_types = list(
  model = col_character(),
  uid = col_character(),
  recommendation = col_character(),
  positive = col_logical(),
  .default = col_double()
)) %>% mutate(dataset = "IUI24")

mbook <- read_csv("processed_data/metrics/metrics_book.csv", col_types = list(
  model = col_character(),
  uid = col_character(),
  recommendation = col_character(),
  positive = col_logical(),
  .default = col_double()
)) %>% mutate(dataset = "Book")

mplaylist <- read_csv("processed_data/metrics/metrics_playlist.csv", col_types = list(
  model = col_character(),
  pid = col_character(),
  recommendation = col_character(),
  positive = col_logical(),
  .default = col_double()
)) %>% mutate(dataset = "SMPD") %>% rename(uid = pid)

metrics <- bind_rows(mmovies, mbook, mplaylist)
rm(mmovies, mbook, mplaylist)
```

```{r}
metrics <- metrics %>%
  mutate(model = case_when(
    model == "gemma2-9b-it" ~ "Gemma2 9B",
    model == "gpt-4o-2024-08-06" ~ "GPT-4o",
    model == "llama3-70b-8192" ~ "Llama3 70B",
    TRUE ~ "Mixtral 8x7B"
  ))
```



```{r}
metrics %>%
  mutate(f1 = ifelse(is.na(f1), 0, f1)) %>%
  group_by(model, dataset, positive) %>%
  summarise(
    mrecall = mean(recall), 
    mprecision = mean(precision), 
    mf1 = (2*mrecall*mprecision)/(mrecall+mprecision),
    .groups = "drop") %>%
  pivot_wider(names_from = positive, values_from = c(mrecall, mprecision, mf1)) %>%
  arrange(model, dataset) %>%
  select(model, dataset, ends_with("TRUE"), ends_with("FALSE")) %>%
  kbl(
    booktabs = T,
    format = "latex",
    caption = "Average Precision and Recall",
    digits = 3,
    col.names = c(
      "Model", "Dataset",
      "AR", "AP", "F1",
      "AR", "AP", "F1"
    )
  ) %>%
  add_header_above(c(" " = 2, "Positive Recs." = 3, "Negative Recs." = 3), bold = T) %>%
  kable_styling(latex_options = "scale_up") %>%
  row_spec(row = 0, bold = T) %>%
  collapse_rows(columns = 1, latex_hline = "full", row_group_label_position = "first") %>% 
  footnote(
    general = c("AR = Average Recall", "AP = Average Precision", "F1 = F1-score of Average Recall and Precision")
  ) %>% cat()
```


```{r}
p <- metrics %>%
  ggplot(aes(x = dataset, y = wcoverage)) +
  geom_boxplot(aes(fill = positive)) +
  geom_hline(yintercept = .5, color = 'red', linetype = 'dashed') +
  scale_y_continuous(breaks = seq(-2, 2, .25), limits = c(-0.6, 1.2)) +
  scale_fill_manual(values = plot_palette) +
  theme_bw() +
  facet_wrap(~ model) +
  labs(title = "",
       x = "Dataset",
       y = "WCov@3",
       fill = "Positive Rec.") +
  theme(legend.position = "top",
        text = element_text(size = 20))

p
```


```{r}
ggsave("wcov_at3_allmodels.pdf", device = "pdf", width = 16, height = 7.5)
```



